#!/bin/bash -xe

FILENAME='AIVD kerstpuzzel 2020 - Marnix Klooster - ingevuld.pdf'

if [ -f "$FILENAME" ]
then
	ccrypt -k ccrypt-key "$FILENAME"
	git add "$FILENAME".cpt
elif [ -f "$FILENAME".cpt ]
then
	ccdecrypt -k ccrypt-key "$FILENAME".cpt
	xdg-open "$FILENAME"
else
	exit 1 # Don't know what to do!
fi
